export const SQL_DB_PROVIDER = 'SEQUELIZE';
export const QUIZ_REPOSITORY = 'QUIZ_REPOSITORY';
export const PHOTO_REPOSITORY = 'PHOTO_REPOSITORY';
export const TYPEORM_DB_PROVIDER = 'TYPEORM_DB_PROVIDER';
export const QUESTION_REPOSITORY = 'QUESTION_REPOSITORY';
